quarkus:
  banner:
    path: banner.txt
  http:
    host: 0.0.0.0
    port: 8081
    cors: true
    limits:
      max-body-size: 700K
    idle-timeout: 5m
  mongodb:
    uuid-representation: STANDARD

mp:
  messaging:
    outgoing:
      currency-profile-events-out:
        connector: smallrye-kafka
        topic: currency-profile-events
    incoming:
      transaction-events:
        connector: smallrye-kafka
        topic: transaction-events
        group:
          id: currency-profile-group
      currency-profile-events-in:
        connector: smallrye-kafka
        topic: currency-profile-events
        group:
          id: currency-profile-group
