quarkus:
  banner:
    path: banner.txt
  http:
    host: 0.0.0.0
    port: 8081
    cors: true
    limits:
      max-body-size: 700K
  quarkus:
    resteasy-reactive:
      path: /api/
  mongodb:
    uuid-representation: STANDARD