quarkus:
  mongodb:
    database: balHomCurrencyDB

  s3:
    sync-client:
      type: apache
    devservices:
      enabled: true
      shared: true

s3:
  bucket:
    name: balhom-bucket

keycloak:
  admin:
    url: http://test
    realm: balhom-realm
    client-id: balhom-api-client
    client-secret: secretKey
