quarkus:
  log:
    level: INFO
  oidc:
    auth-server-url: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:balhom-realm}
    client-id: ${KEYCLOAK_CLIENT:balhom-client}
    application-type: service
  mongodb:
    connection-string: ${MONGODB_URL}
    database: ${MONGODB_DB:balHomCurrencyDB}

kafka:
  bootstrap:
    servers: ${KAFKA_SERVERS}

mp:
  messaging:
    outgoing:
      currency-profile-events:
        connector: smallrye-kafka
        topic: currency-profile-events
