quarkus:
  mongodb:
    database: balHomCurrencyDB

  s3:
    sync-client:
      type: apache
    devservices:
      enabled: true
      shared: true
      buckets: balhom-currency-api-bucket
    bucket:
      name: balhom-currency-api-bucket

mp:
  messaging:
    outgoing:
      currency-profile-events-out:
        connector: smallrye-kafka
        topic: currency-profile-events
    incoming:
      transaction-events:
        connector: smallrye-kafka
        topic: transaction-events
        group:
          id: currency-profile-group
      currency-profile-events-in:
        connector: smallrye-kafka
        topic: currency-profile-events
        group:
          id: currency-profile-group

keycloak:
  admin:
    url: http://test
    realm: balhom-realm
    client-id: balhom-api-client
    client-secret: secretKey
